repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: check-json
        exclude: .devcontainer/devcontainer.json
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: pretty-format-json
        args:
          - "--autofix"
        exclude: .devcontainer/devcontainer.json
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-executables-have-shebangs
      - id: detect-private-key
      - id: check-added-large-files
        args:
          - "--maxkb=5000"
      - id: detect-aws-credentials
        args:
          - "--allow-missing-credentials"
