name: Test-flow
run-name: >-
  ${{ github.event.issue.number && format('test_flow | PR-{0}', github.event.issue.number)
  || 'Test Deployment' }}

permissions: read-all

on:
  issue_comment:
    types: [created]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-pipeline:
    runs-on: ubuntu-latest
    name: test-workflow
    permissions: write-all


    ############## Test your branch by pushing to the test branch of this repo ############################
    steps:
      - name: Run Composite Module
        uses: TRI-IE/web-app-infra@test

      - name: Terraform destroy
        if: always()
        id: destroy
        shell: bash
        run: terraform destroy -auto-approve
        continue-on-error: true
        working-directory: terraform
